### ISSUE TITLE
Case (in)sensitive support

### ISSUE THREAD

**Issue by ilazarevski** [DynamicODataToSQL/DynamicODataToSQL#11]
Support for case (in)sensitive for default supported string operations via parameter to the main method.

**Comment by maciejpieprzyk** [comment]
Hi @ilazarevski, @vaibhav-goyal, I created [Pull Request](https://github.com/DynamicODataToSQL/DynamicODataToSQL/pull/18) with a change that will allow using **toupper** and **tolower** OData functions in $filter (enabling case-sensitive in query). Just letting you know, because this could potentially fulfill this feature request.

**Comment by maciejpieprzyk** [comment]
Hi, @ilazarevski can you let me know If toupper and tolower OData functions are sufficient for you? They were added to the latest release 1.0.7

**Comment by ilazarevski** [comment]
Hi @maciejpieprzyk Thank you for letting me know. I will check with my team and try the enchantment.
